---
title: "Homework 4 P 2"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
```
```{r}
nyoaa_df = read_csv("./Data/nynoaadat.csv")%>% 
  janitor::clean_names()%>% 
  drop_na() %>% 
  mutate(date = as.Date(date)) %>% 
  filter(
    prcp != 0,
    snow != 0,
    snwd != 0
  ) %>% 
  mutate(month = format(date, "%m"),
         year = format(date, "%y"))
set.seed(222)
random_nyoaa_df = nyoaa_df[sample(nrow(nyoaa_df), 1000),]
```

Column {data-width=650}
-----------------------------------------------------------------------

### Minimum Temperature over time and parcipitation

```{r}
random_nyoaa_df %>% 
  plot_ly(
    x = ~date, y = ~tmin, type = "scatter", mode = "markers",
    color = ~prcp)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Distribution of snow depth by month

```{r}
random_nyoaa_df %>% 
  plot_ly (
    x =~ month, y=~snwd, type = "box"
  )
```

### Cumulative parcipication by year

```{r}
random_nyoaa_df %>% 
  plot_ly (
    x =~ year, y=~prcp, type = "bar"
  )
```

