---
title: "Academic and Professional Experience"
output: 
  html_document:
    toc: true
    toc_float: true
---
# EDUCATION: 

 * Columbia University- M.S. in Biostatistics Candidate, Public Health and Data Science Track Part-time, Aug 2022- Current
 
 * Bucknell University- B.S. in Chemical Engineering, Biology Concentration and Art History Minor Aug 2017-May 2021
 
# CERTIFICATIONS:

* Medical Research Management-Clinical Research Professional Training Certificate Apr 2022- May 2022 

* Barnett International- 10-Week CRA & CRC Program Certificate Jul 2022 – Aug 2022

# PROFESSIONAL EXPERIENCE:

## Merck & Co., Rahway, NJ 
### Clinical Scientist, Infectious Diseases & Vaccines Nov 2023-Current
### Associate Clinical Scientist, Infectious Diseases & Vaccines Sep 2022-Oct 2023
  *Medical data monitoring for HVP Vaccine trial
### Clinical Trial Coordinator Jun 2021- Sep 2022

  * Responsible for 83 clinical trial sites across 4 therapeutic areas (COVID-19 antiviral, end stage renal disease,  colorectal cancer, and vaccines) including preparing, distributing, tracking, and archiving essential regulatory clinical 
documents, data, and quality control plans in the electronic Trial Master File. 

  * Collaborates cross-functionally with site staff and the sponsor country level team for 4 clinical trials in order to set and maintain site timelines with the use of Spotfire dashboards. 
  * Develops packages for submission to the IRB/ERC and FDA and has completed over 50 packages.
  * Promotes continuous improvement as a Windows 10 SME presenting monthly tips, editor for the Global Clinical Trial Operations newsletter revising 5-10 articles each quarter, intern mentor, and reverse mentor.
  * Trains new hires through maintaining and developing a mock clinical trial with written curriculum for 9 clinical 
research milestones, compiling an onboarding guide, creating a welcome video, and through one-on-one mentoring. 

### Medical Data Analytics Center Gig, Global Medical and Scientific Affairs Mar 2022-Aug 2022
  * Identify scientific leaders and high treaters for Respiratory Syncytial Virus as potential investigators through refining medical claims data using the Merck Real World Data Exchange and SQL.
  * Manage data from 807 clinical hematology sites and use Excel VBA to narrow clinical trial site search to 318 sites. 

### Clinical Sciences Study Management, Intern May 2020-Aug 2020
  *Researched and presented to leadership on minority enrollment in clinical trials and discussed 4 ways of increasing  minority recruitment.
  *Drafted and reviewed the adjudication charter for a cardiovascular phase 2/3 clinical trial and assisted with the  medical monitoring of a neurology clinical trial using JReview.

## Johnson & Johnson, Ethicon Somerville, NJ 

### Product Performance Evaluation Engineering Intern May 2018-Aug 2018, May 2019-Aug 2019
  * Conducted a experimental study, wrote a research paper, and presented on the topography and tensile strength of 120 suture samples.
  * Produced and executed a GMP Operational Protocol for the validation and assessment of process controls of water baths with a ±0.1˚C tolerance using Resistance Temperature Detectors to conduct temperature mapping.
  * Examined R&D data collection and experimental design in order to establish a R&D electronic laboratory notebook
  * Authored a test method to assess adhesive strength of Vistaseal™ compared to 2 competing fibrin sealants.
  * Completed 3 GLP adhesive strength tests and statistical data analysis for the Performance Evaluation and Biosurgery departments to be used for commercial claims and presented official test results to marketing representatives.

# PROJECTS:

## Mather Research Group-Undergraduate Research and Honors Thesis, Bucknell University Aug 2019-May 2021 

  * Thesis: Controlled Release of Small Molecule Drug Models Based on the Diameter of Polymeric Fibers Fabricated Via Electrospinning
  * Investigated and manipulated biodegradable electrospun nanofiber structures for use in controlled drug delivery.

## Bucknell Chemical Engineering & Jackass Brewing Company- Capstone Project Jan 2021-May 2021

  * Established cost effective methods for measuring and optimizing yeast viability and vitality during the brewing process. 
  * Completed a scale-up plan for yeast propagation to decrease the quantity of new yeast needed for each batch of beer.
  
## TECHNICAL SKILLS:
* Clinical: ICH-GCP and FDA regulations, SIP, Spectrum, ALMAC, Oracle Clinical Analytics, Medical Monitoring
* Other Skills: GMP, GLP, Aspen HYSYS/Properties, Minitab, Excel VBA and Macros, MATLAB, JReview, Spotfire, VeevaVault, ImageJ, Loop-Pro, Simulink, R, SQL